export const GET_USER_DATA_lOADING = "GET_USER_DATA_lOADING";
export const GET_USER_DATA_SUCESS = "GET_USER_DATA_SUCESS";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";

export const INCREMENT_AMT = "INCREMENT_AMT";
export const DECREMENT_AMT = "DECREMENT_AMT";
export const INCREMENT_POINTS = "INCREMENT_POINTS";
