export const DATA_FETCHING_LOADING = "DATA_FETCHING_LOADING";
export const DATA_FATCHING_SUCESS = "ATA_FATCHING_SUCESS";
export const DATA_FATCHING_FAILURE = "ATA_FATCHING_FAILURE";
export const DATA_FETCHING_LOADING_By_ID = "DATA_FETCHING_LOADING_By_ID";
export const DATA_FATCHING_SUCESS_By_ID = "ATA_FATCHING_SUCESS_By_ID";
export const DATA_FATCHING_FAILURE_By_ID = "ATA_FATCHING_FAILURE_By_ID";
