// Action Types
export const INCREMENTCOUNT = "INCREMENTCOUNT";
export const DECREMENTCOUNT = "DECREMENTCOUNT";
export const RESETCOUNT = "RESETCOUNT";
//Fechingtypes
export const GET_LANGUAGE_LOADING = "GET_LANGUAGE_LOADING";
export const GET_LANGUAGE_SUCESS = "GET_LANGUAGE_SUCESS";
export const GET_LANGUAGE_FAILIAURE = "GET_LANGUAGE_FAILIAURE";